package comovamos;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
/*
 * Parte Elaborada por Oscar
 * Correspondiente a la Entidad (Catalogos) COM_Plantilla
 * Funciones: Altas-Bajas-Actualizaciones-Busquedas
 * ~NO~ Borrar
 * Faltan Cosas
 */
public class frmPlantilla extends javax.swing.JInternalFrame {
java.util.Date fecha = new java.util.Date();
    DefaultTableModel modelo = new DefaultTableModel();
    Connection cnn;
    String sqli = null;
    PreparedStatement psi;
    ResultSet rsi;
    int filas;
    int PLA_id= 0, PLA_Indicador= 0,PLA_Usuario = 0;;
    String PLA_NomPlantilla = "",IND_Plantillacol = "",PLA_Descripcion = "",PLA_Periodo = "", codigo  = "";
    String nombreColumnas[]={"PLA_id","PLA_NomPlantilla","PLA_Descripcion","PLA_Periodo","PLA_Plantilla"};
    boolean reg, autoreg,salidareg;
    String codmod;
    int MAXIMIZED_BOTH;

    /** Creates new form frmPlantilla */
    public frmPlantilla() {
        initComponents();
        Cargar();
    }
void Cargar(){
        String Usuario ="ozkar";
        String Pass ="";
        Plantilla.cargarDriver();
        Plantilla.conexionBaseDatos(Usuario, Pass);
        modelo.setDataVector(Plantilla.Reportar(), nombreColumnas);
    }
    void LimpiarTxts(){
            Txt_id.setText("");
            TxtNomPlan.setText("");
            TxtDescripcion.setText("");
            ComboNomIndi.removeAllItems();
            TxtPeriodo.setText("");            
            TxtIndicador.setText("");
            TxtUsuario.setText("");
    }
    void Habilitar(){
        Txt_id.setEnabled(true);
        TxtNomPlan.setEnabled(true);
        TxtDescripcion.setEnabled(true);
        TxtPeriodo.setEnabled(true);
        TxtIndicador.setEnabled(true);
        TxtUsuario.setEnabled(true);
        ComboNomIndi.setEnabled(true);
    }
    void AgregarItemsPlantilla(){
        try{
            sqli = "SELECT * FROM COM_Plantilla ";
            psi = Plantilla.cn.prepareStatement(sqli);
            rsi = psi.executeQuery();
            while(rsi.next()){
                ComboNomIndi.addItem(rsi.getObject(2));
            }
         }
        catch(SQLException e){
             JOptionPane.showMessageDialog(null,"Error en SQL "+e.getMessage());
        }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Txt_id = new javax.swing.JTextField();
        TxtNomPlan = new javax.swing.JTextField();
        TxtDescripcion = new javax.swing.JTextField();
        TxtPeriodo = new javax.swing.JTextField();
        TxtIndicador = new javax.swing.JTextField();
        TxtUsuario = new javax.swing.JTextField();
        ComboNomIndi = new javax.swing.JComboBox();
        PanelLabel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ScrollPlantilla = new javax.swing.JScrollPane();
        TablaPlantilla = new javax.swing.JTable();
        ToolPlantilla = new javax.swing.JToolBar();
        NuevoPlantilla = new javax.swing.JButton();
        ModificarPlantilla = new javax.swing.JButton();
        AgregarPlantilla = new javax.swing.JButton();
        EliminarPlantilla = new javax.swing.JButton();
        BuscarPlantilla = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Catalogo de Plantilla-Encuestas");

        Txt_id.setEnabled(false);
        Txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_idActionPerformed(evt);
            }
        });

        TxtNomPlan.setEnabled(false);
        TxtNomPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomPlanActionPerformed(evt);
            }
        });

        TxtDescripcion.setEnabled(false);

        TxtPeriodo.setEnabled(false);
        TxtPeriodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPeriodoKeyTyped(evt);
            }
        });

        TxtIndicador.setEnabled(false);
        TxtIndicador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIndicadorKeyTyped(evt);
            }
        });

        TxtUsuario.setEnabled(false);
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyTyped(evt);
            }
        });

        ComboNomIndi.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNomPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(Txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(TxtPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(TxtIndicador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(ComboNomIndi, 0, 199, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtNomPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboNomIndi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setText("Plantilla Llave");

        jLabel2.setText("NombrePlantilla");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Periodo");

        jLabel6.setText("PLA_Indicador");

        jLabel7.setText("PLA_Usuario");

        javax.swing.GroupLayout PanelLabelLayout = new javax.swing.GroupLayout(PanelLabel);
        PanelLabel.setLayout(PanelLabelLayout);
        PanelLabelLayout.setHorizontalGroup(
            PanelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLabelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(PanelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLabelLayout.createSequentialGroup()
                        .addGroup(PanelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLabelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLabelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        PanelLabelLayout.setVerticalGroup(
            PanelLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        TablaPlantilla.setModel(modelo);
        ScrollPlantilla.setViewportView(TablaPlantilla);

        ToolPlantilla.setRollover(true);

        NuevoPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comovamos/Iconos/Agregar.png"))); // NOI18N
        NuevoPlantilla.setText("Nuevo");
        NuevoPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoPlantillaActionPerformed(evt);
            }
        });
        ToolPlantilla.add(NuevoPlantilla);

        ModificarPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comovamos/Iconos/Modificar.png"))); // NOI18N
        ModificarPlantilla.setText("Modificar");
        ModificarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPlantillaActionPerformed(evt);
            }
        });
        ToolPlantilla.add(ModificarPlantilla);

        AgregarPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comovamos/Iconos/Guardar.png"))); // NOI18N
        AgregarPlantilla.setText("Agregar");
        AgregarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPlantillaActionPerformed(evt);
            }
        });
        ToolPlantilla.add(AgregarPlantilla);

        EliminarPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comovamos/Iconos/Eliminar.png"))); // NOI18N
        EliminarPlantilla.setText("Eliminar");
        EliminarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPlantillaActionPerformed(evt);
            }
        });
        ToolPlantilla.add(EliminarPlantilla);

        BuscarPlantilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comovamos/Iconos/search.png"))); // NOI18N
        BuscarPlantilla.setText("Buscar");
        BuscarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPlantillaActionPerformed(evt);
            }
        });
        ToolPlantilla.add(BuscarPlantilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(PanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_idActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Txt_idActionPerformed

    private void TxtNomPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomPlanActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_TxtNomPlanActionPerformed

    private void TxtPeriodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPeriodoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'a' || car>'z') && (car<'A' || car>'Z')) evt.consume();
}//GEN-LAST:event_TxtPeriodoKeyTyped

    private void TxtIndicadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIndicadorKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
}//GEN-LAST:event_TxtIndicadorKeyTyped

    private void NuevoPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPlantillaActionPerformed
        LimpiarTxts();
        reg = true;
        rsi = null;
        ComboNomIndi.removeAllItems();
        try {
            rsi = Plantilla.ps.executeQuery("SELECT * FROM COM_Plantilla ");
            while(rsi.next()){
                ComboNomIndi.addItem(rsi.getObject(2));
            }
        } catch (SQLException ex){
            Logger.getLogger(frmPlantilla.class.getName()).log(Level.SEVERE, null, ex);
        }
        Habilitar();
        AgregarItemsPlantilla();
        Txt_id.setEnabled(false);
        TxtNomPlan.requestFocus();
}//GEN-LAST:event_NuevoPlantillaActionPerformed

    private void ModificarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPlantillaActionPerformed
        LimpiarTxts();
        AgregarItemsPlantilla();
        Habilitar();
        codmod=JOptionPane.showInputDialog("Ingrese el código del Plantilla a Buscar: ");
        if(Plantilla.BuscarPlantilla(codmod)) {
            Txt_id.setText(String.valueOf(Plantilla.getPLA_id()));
            TxtNomPlan.setText(Plantilla.getPLA_NomPlantilla());
            TxtDescripcion.setText(Plantilla.getPLA_Descripcion());
            TxtPeriodo.setText(Plantilla.getPLA_Periodo());
            TxtIndicador.setText(String.valueOf(Plantilla.getPLA_Indicador()));
            TxtUsuario.setText(String.valueOf(Plantilla.getPLA_Usuario()));
            reg = false;
        } else{
            JOptionPane.showMessageDialog(null,"El Código del Plantilla No fue encontrado");
            reg = true;
        }
}//GEN-LAST:event_ModificarPlantillaActionPerformed

    private void AgregarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPlantillaActionPerformed
        if(!TxtDescripcion.getText().equals("") && !TxtNomPlan.getText().equals("") && !TxtPeriodo.getText().equals("") && !TxtIndicador.getText().equals("")) {
            //PLA_NomPlantilla = TxtNombre.getText();
            //PLA_NomPlantilla = (String) ComboNomIndi.getSelectedItem();
            PLA_NomPlantilla = TxtNomPlan.getText();
            JOptionPane.showMessageDialog(null,"Campo "+ PLA_NomPlantilla);
            PLA_Descripcion = TxtDescripcion.getText();
            PLA_Periodo = TxtPeriodo.getText();
            PLA_Indicador = Integer.parseInt(TxtIndicador.getText());
            PLA_Usuario = Integer.parseInt(TxtUsuario.getText());
            Plantilla ali = new Plantilla(PLA_id,PLA_NomPlantilla,PLA_Descripcion,PLA_Periodo,PLA_Indicador,PLA_Usuario);
            if(reg) {
                Plantilla.RegistrarPlantilla();
                JOptionPane.showMessageDialog(null,"Plantilla Registrado");
                modelo.setDataVector(Plantilla.Reportar(), nombreColumnas);
            } else {
                Plantilla.ModificarPlantilla(codmod);
                JOptionPane.showMessageDialog(null,"Plantilla Modificado");
                modelo.setDataVector(Plantilla.Reportar(), nombreColumnas);
            }
        } else    JOptionPane.showMessageDialog(null,"Campos Vacios, Favor de Llenar Datos Correspondientes");
}//GEN-LAST:event_AgregarPlantillaActionPerformed

    private void EliminarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPlantillaActionPerformed
        codigo=JOptionPane.showInputDialog("Ingrese el código del Plantilla a Buscar:  ");
        if(Plantilla.BuscarPlantilla(codigo)) {
            Txt_id.setText(String.valueOf(Plantilla.getPLA_id()));
            TxtNomPlan.setText(Plantilla.getPLA_NomPlantilla());
            TxtDescripcion.setText(Plantilla.getPLA_Descripcion());
            TxtPeriodo.setText(Plantilla.getPLA_Periodo());
            TxtIndicador.setText(String.valueOf(Plantilla.getPLA_Indicador()));
            int resp= JOptionPane.showConfirmDialog(this,"Esta Seguro de Eliminar Regitro ","Eliminar Dato",JOptionPane.YES_NO_OPTION );
            if( resp == JOptionPane.YES_OPTION ){
                Plantilla.EliminaPlantilla(codigo);
                JOptionPane.showMessageDialog(this,"Registro Eliminado");
                modelo.setDataVector(Plantilla.Reportar(), nombreColumnas);
            }
            LimpiarTxts();
        } else JOptionPane.showMessageDialog(null,"El Código del Plantilla No fue encontrado");
}//GEN-LAST:event_EliminarPlantillaActionPerformed

    private void BuscarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPlantillaActionPerformed
        codigo=JOptionPane.showInputDialog("Ingrese el código del Plantilla a Buscar:  ");
        Plantilla.BuscarPlantilla(codigo);
        if(Plantilla.BuscarPlantilla(codigo)){
            Txt_id.setText(String.valueOf(Plantilla.getPLA_id()));
            TxtNomPlan.setText(Plantilla.getPLA_NomPlantilla());
            TxtDescripcion.setText(Plantilla.getPLA_Descripcion());
            TxtPeriodo.setText(Plantilla.getPLA_Periodo());
            TxtIndicador.setText(String.valueOf(Plantilla.getPLA_Indicador()));
            TxtUsuario.setText(String.valueOf(Plantilla.getPLA_Usuario()));
        } else{
            JOptionPane.showMessageDialog(null,"El Código del Plantilla No fue encontrado");
            LimpiarTxts();
            modelo.setDataVector(Plantilla.Reportar(), nombreColumnas);
        }
        Plantilla.Reportar();

        JCheckBox comboBox = new JCheckBox();
        JComboBox comboBox2 =new JComboBox();

        try {
            rsi = Plantilla.ps.executeQuery("SELECT * FROM COM_Plantilla ");
            while(rsi.next()){
                comboBox.setSelected(true);
                comboBox2.addItem(rsi.getObject(3));
            }
        } catch (SQLException ex){
            Logger.getLogger(frmPlantilla.class.getName()).log(Level.SEVERE, null, ex);
        }

        TablaPlantilla.setCellEditor(new DefaultCellEditor(comboBox2)); //enfasis en esta linea!!!!
        DefaultCellEditor defaultCellEditor=new DefaultCellEditor(comboBox2);
        TablaPlantilla.getColumnModel().getColumn(3).setCellEditor(defaultCellEditor);
        AgregarItemsPlantilla();
}//GEN-LAST:event_BuscarPlantillaActionPerformed

    private void TxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPlantilla;
    private javax.swing.JButton BuscarPlantilla;
    private javax.swing.JComboBox ComboNomIndi;
    private javax.swing.JButton EliminarPlantilla;
    private javax.swing.JButton ModificarPlantilla;
    private javax.swing.JButton NuevoPlantilla;
    private javax.swing.JPanel PanelLabel;
    private javax.swing.JScrollPane ScrollPlantilla;
    private javax.swing.JTable TablaPlantilla;
    private javax.swing.JToolBar ToolPlantilla;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtIndicador;
    private javax.swing.JTextField TxtNomPlan;
    private javax.swing.JTextField TxtPeriodo;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JTextField Txt_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
