package comovamos;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VDatos.java
 *
 * Created on 29-oct-2012, 17:20:47
 */
/**
 *
 * @author chocobo
 */
public class VDatos extends javax.swing.JFrame {
String campos, tablas, condicion;
    
    public VDatos(String campos, String tablas, String condicion) {
        initComponents();
        this.campos=campos;
        this.tablas=tablas;
        this.condicion=condicion;
    }
     public VDatos() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setColumnSelectionAllowed(false);
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setEditingColumn(0);
        tabla.setEditingRow(0);
        tabla.setFillsViewportHeight(true);
        tabla.setFocusable(false);
        tabla.setName("tabla"); // NOI18N
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Datos de gráfica");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void ctabla(){
         modelo = new DefaultTableModel();
        tabla.setModel(modelo);
        try {
            //tabla.setEnabled(false);
            con=new Conexion("tallerii1202","paul123");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se pudo acceder al servidor de la Base de Datos, verifique que tiene conexion con acceso al servidor", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        res=con.select(con, campos, tablas, condicion);
        con.desconectar();
        int n=1;
                
      
        try {//obtenemos los nombres de las columnas y armamos la tabla
         tdatos=new String[res.getMetaData().getColumnCount()];
         while(n<(res.getMetaData().getColumnCount()+1)){   
            modelo.addColumn(res.getMetaData().getColumnLabel(n));
            
            n++;}
            int p=0;
         for(int f=1;f<n;f++) {
            tdatos[p]=res.getMetaData().getColumnTypeName(f);
            p++;
        }	
                  	
                 
        } catch (SQLException ex) {
            Logger.getLogger(VDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
      /////////////////////obtener datos de la consulta y meterlos a la tabla
         try {
             
             datos=new String[res.getMetaData().getColumnCount()];
                                
                while(res.next()){
                    for(int i=0;i<res.getMetaData().getColumnCount();i++){
                        System.out.println(""+tdatos[i]);
                        if(tdatos[i]=="INT"){datos[i]=String.valueOf(res.getInt(i+1));}
                        if(tdatos[i]=="VARCHAR"){datos[i]=res.getString(i+1);}
                        if(tdatos[i]=="DATETIME"){datos[i]=""+res.getDate(i+1).getDay()+"/"+res.getDate(i+1).getMonth()+"/"+(res.getDate(i+1).getYear()+1900);}
                        
                    }
                    modelo.addRow(datos);
                }
                                 
        } catch (SQLException ex) {
            Logger.getLogger(VDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(int f=0;f<7;f++) {
            System.out.println("Dato: "+(f+1)+": "+datos[f]);
            
        }	
        
    }
private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    ctabla();
   
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel modelo;
    Conexion con;
    ResultSet res;
    String tdatos[],datos[];
}
